### PR TITLE
fix: generalize labels indexed by ES

### LINKED ISSUE #28: Enhance statistics report
Generalize annotation labels that are available on Kibana.
Currently it's necessary to hardcode at
https://github.com/acesso-io/techcore-cvat/blob/f9024cc9967099fe7ac9666a5dd8c8f7ae021101/cvat-ui/src/actions/annotation-actions.ts#L85 
which labels we want ES to index

### PR DESCRIPTION
**Pull request by rafascm**
Fixes #28

### CODE REVIEW

File: cvat-ui/src/actions/annotation-actions.ts [hunk 1]
```diff
@@ -82,16 +82,25 @@ export function computeZRange(states: any[]): number[] {
     return [minZ, maxZ];
 }
 
+interface ILabelType extends Object {
+    total: number
+}
+
+function getMetricTags(labels: Record<string, ILabelType>): Record<string, number> {
```
Comment (hs-pedro) [inline cvat-ui/src/actions/annotation-actions.ts:89]: If `labels` is unitialized it will be `undefined` and `Object.entries(labels)` is going to throw an Exception. We can guard ourselves by assigning a default value on args:
```suggestion
function getMetricTags(labels: Record<string, ILabelType> = {}): Record<string, number> {
```

**Review by hs-pedro — APPROVED** [review]
LGTM, minor comment, once fixed you can integrate
